### ISSUE TITLE
I tried to compile lineageos 14.1 using your Makefile, but I encountered this mistake. Can you help me solve it?

### ISSUE THREAD

**Issue by him1234** [Spirtix/android_device_huawei_HWPLK#2]
frameworks/av/camera/cameraserver/Android.mk:18: Target has integrated cameraserver into mediaserver. This is weakening security measures introduced in 7.0
find: `/home/android/los/out/target/common/obj/SHARED_LIBRARIES/libwifi-hal-mock_intermediates': 没有那个文件或目录
vendor/cm/build/tasks/kernel.mk:159: ***************************************************************
vendor/cm/build/tasks/kernel.mk:160: * Using prebuilt kernel binary instead of source              *
vendor/cm/build/tasks/kernel.mk:161: * THIS IS DEPRECATED, AND WILL BE DISCONTINUED                *
vendor/cm/build/tasks/kernel.mk:162: * Please configure your device to download the kernel         *
vendor/cm/build/tasks/kernel.mk:163: * source repository to kernel/huawei/HWPLK
vendor/cm/build/tasks/kernel.mk:164: * for more information                                        *
vendor/cm/build/tasks/kernel.mk:165: ***************************************************************
build/core/Makefile:34: warning: overriding commands for target `/home/android/los/out/target/product/HWPLK/system/etc/permissions/android.software.live_wallpaper.xml'
build/core/base_rules.mk:320: warning: ignoring old commands for target `/home/android/los/out/target/product/HWPLK/system/etc/permissions/android.software.live_wallpaper.xml'
build/core/Makefile:34: warning: overriding commands for target `/home/android/los/out/target/product/HWPLK/system/etc/permissions/com.android.location.provider.xml'
build/core/base_rules.mk:320: warning: ignoring old commands for target `/home/android/los/out/target/product/HWPLK/system/etc/permissions/com.android.location.provider.xml'
build/core/Makefile:34: warning: overriding commands for target `/home/android/los/out/target/product/HWPLK/system/etc/permissions/com.android.media.remotedisplay.xml'
build/core/base_rules.mk:320: warning: ignoring old commands for target `/home/android/los/out/target/product/HWPLK/system/etc/permissions/com.android.media.remotedisplay.xml'
build/core/Makefile:34: warning: overriding commands for target `/home/android/los/out/target/product/HWPLK/system/etc/permissions/com.android.mediadrm.signer.xml'
build/core/base_rules.mk:320: warning: ignoring old commands for target `/home/android/los/out/target/product/HWPLK/system/etc/permissions/com.android.mediadrm.signer.xml'
build/core/Makefile:34: warning: overriding commands for target `/home/android/los/out/target/product/HWPLK/system/etc/permissions/platform.xml'
build/core/base_rules.mk:320: warning: ignoring old commands for target `/home/android/los/out/target/product/HWPLK/system/etc/permissions/platform.xml'
Starting build with ninja
ninja: Entering directory `.'
[ 25% 1/4] Target buildinfo: /home/android/los/out/target/product/HWPLK/obj/ETC/system_build_prop_intermediates/build.prop
Target buildinfo from: device/huawei/HWPLK/system.prop
[100% 4/4] Target boot image: /home/android/los/out/target/product/HWPLK/boot.img
FAILED: /bin/bash -c "(/home/android/los/out/host/linux-x86/bin/mkbootimg  --kernel /home/android/los/out/target/product/HWPLK/kernel --ramdisk /home/android/los/out/target/product/HWPLK/ramdisk.img --base 0x00678000 --pagesize 2048 --cmdline \"androidboot.hardware=hi3635 androidboot.selinux=permissive no_console_suspend=1 mem=3072M coherent_pool=512K mmcparts=mmcblk0:p1(vrl),p2(vrl_backup),p6(modemnvm_factory),p9(splash),p10(modemnvm_backup),p11(modemnvm_img),p12(modemnvm_system),p14(3rdmodemnvm),p15(3rdmodemnvmback),p17(modem_om),p20(modemnvm_update),p30(modem),p31(modem_dsp),p32(dfx),p33(3rdmodem) cpuidle_sysfs_switch=1 buildvariant=userdebug\" --os_version 7.1.2 --os_patch_level 2018-06-05 --kernel_offset 0x00008000 --ramdisk_offset 0x07588000 --tags_offset 0xffb88000 --output /home/android/los/out/target/product/HWPLK/boot.img ) && (size=\$(for i in /home/android/los/out/target/product/HWPLK/boot.img; do stat --format \"%s\" \"\$i\" | tr -d '\\n'; echo +; done; echo 0); total=\$(( \$( echo \"\$size\" ) )); printname=\$(echo -n \"/home/android/los/out/target/product/HWPLK/boot.img\" | tr \" \" +); img_blocksize=4224; twoblocks=\$((img_blocksize * 2)); onepct=\$(((((11806113792 / 100) - 1) / img_blocksize + 1) * img_blocksize)); reserve=\$((twoblocks > onepct ? twoblocks : onepct)); maxsize=\$((11806113792 - reserve)); echo \"\$printname maxsize=\$maxsize blocksize=\$img_blocksize total=\$total reserve=\$reserve\"; if [ \"\$total\" -gt \"\$maxsize\" ]; then echo \"error: \$printname too large (\$total > [11806113792 - \$reserve])\"; false; elif [ \"\$total\" -gt \$((maxsize - 32768)) ]; then echo \"WARNING: \$printname approaching size limit (\$total now; limit \$maxsize)\"; fi )"
Traceback (most recent call last):
  File "/home/android/los/out/host/linux-x86/bin/mkbootimg", line 208, in <module>
    main()
  File "/home/android/los/out/host/linux-x86/bin/mkbootimg", line 199, in main
    img_id = write_header(args)
  File "/home/android/los/out/host/linux-x86/bin/mkbootimg", line 77, in write_header
    (args.os_version << 11) | args.os_patch_level)) # os version and patch level
struct.error: 'I' format requires 0 <= number <= 4294967295
ninja: build stopped: subcommand failed.
build/core/ninja.mk:151: recipe for target 'ninja_wrapper' failed
make: *** [ninja_wrapper] Error 1

#### make failed to build some targets (22 seconds) ####

android@android-MS-7918:~/los$

**Comment by him1234** [comment]
I think the size of the generated boot.img is larger than the size set in device, but after I tried to modify it, I found it was still the same mistake. Please help me solve it. Thank you very much！！！！

**Comment by Spirtix** [comment]
The offset is bigger than int32, so it's not buildable with the python script. Replace it with the binary mkbootimg and replace the default makefile.
https://drive.google.com/drive/folders/1rps5YchSUHd1_6bS7RJ8f7pW3vqhKKV-?usp=sharing

**Comment by him1234** [comment]
Thank you ！ And Which directory is the makefile replaced?
