### ISSUE TITLE
I tried to compile Lineageos 13 using your device-tree but there were some errors when the system started. Can you help me?

### ISSUE THREAD

**Issue by him1234** [Spirtix/android_device_huawei_HWPLK#7]
This is system log. I found that service media.audio can't be started. How can I solve this problem?
Can you help me? Thank you very much!!!!!!

**Comment by trautamaki** [comment]
You need vendor files.


07-14 18:43:03.762  2944  2944 E linker  : Shim lib "/system/lib/libshim_camera_client.so" can not be loaded, ignoring.

07-14 18:43:03.762  2944  2944 E linker  : Shim lib "/system/lib/libshim_media.so" can not be loaded, ignoring.

07-14 18:43:03.762  2944  2944 E linker  : Shim lib "/system/lib/libshim_hwui.so" can not be loaded, ignoring.

07-14 18:43:03.794  2933  2933 I DEBUG   : debuggerd: starting

07-14 18:43:03.794  2942  2942 I ImagingSystem: CImagingSystemDriver::CImagingSystemDriver(char*, char*, bool) enter ! 

07-14 18:43:03.795  2942  2942 E ImagingSystem: failed to dlopen(/system/lib/hwcam/hwcam.hi3635.m.PLK.so)!

**Comment by Spirtix** [comment]
Did you use vendor for LOS13?

**Comment by him1234** [comment]
Yes, I used vendor in vendor/readme.txt in device-tree, but it was extracted from P8 ROM.and Now the system has been started , but cameras, microphones, and WIFI can not be used, and there is no sound. How can I solve this problem?  

###  This is the system log
### **[logcat.log](https://github.com/Spirtix/android_device_huawei_HWPLK/files/2196898/logcat.log)**


_Thanks to T1mpp4 and Spirtix_

**Comment by Spirtix** [comment]
Use the right vendor. The one in device tree is obsolete.

**Comment by him1234** [comment]
Oh, thank you. I'm going to find a suitable new vendor.

**Comment by Spirtix** [comment]
It is my repos...
https://github.com/Spirtix/android_vendor_huawei_HWPLK/tree/master?files=1

**Comment by him1234** [comment]
Thank you very much！
I will use it and make the LOS again.

**Comment by him1234** [comment]
I tried to compile Omni ROM to HWPLK, but after the compilation, but it could not start. I found that Media server was died from logcat, but I didn't know how to solve it. Can you help me? 
**This is the logcat:**
### [logcat.log](https://github.com/Spirtix/android_device_huawei_HWPLK/files/2210349/logcat.log)

Thank you very much!!!!!!!!

**Comment by Spirtix** [comment]
This is device tree for LineageOS, if you want to help with other ROMs you can contact me via xda private messages.

**Comment by him1234** [comment]
OK,Thank you

**Comment by him1234** [comment]
I have sent you a private letter on **XDA**, please reply to me after receiving it. Thank you!
